baseURL = 'https://daily.douchi.space/public'
languageCode = 'en-us'
title = '椒盐 daily'
theme = "paper"
description = "介于日常碎碎念和博客之间的对时间流逝的死缠烂打。"
paginate = 100

# https://themes.gohugo.io/themes/hugo-paper/

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  mastodon = 'https://douchi.space/@mtfront' 
  bluesky = 'mtfront.bsky.social'               # https://bsky.app/profile/YOUR_BLUESKY_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://media.douchi.space/douchi/accounts/avatars/000/000/001/original/40c89c24d6524a14.gif'                 # gravatar email or image url
  name = '椒盐豆豉'
  bio = '介于日常碎碎念和博客之间的对时间流逝的死缠烂打。'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "https://media.douchi.space/douchi/accounts/avatars/000/000/001/original/40c89c24d6524a14.gif"                   # customize the default favicon
  appleTouchIcon = "https://media.douchi.space/douchi/accounts/avatars/000/000/001/original/40c89c24d6524a14.gif"   # inoreader seems to use this

  # RTL supprot
  # direction = "rtl"                         # RTL support for Right-to-left languages

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'paraiso-light'     # style demos https://pygments.org/demo/

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://blog.douchi.space"
    weight = 10
